spring:
  com:
    sanjay:
      springmysql:
        controller: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myschema
    username: root
    password: root
  jpa:
    #hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
name: springJPA-YAML
server:
  port: 8083
